### ISSUE TITLE
Might this be ported to the Atom editor?

### ISSUE THREAD

**Issue by starbg** [NielsLiisberg/RPG-for-VSCode#3]
https://atom.io/

**Comment by NielsLiisberg** [comment]
It should be possible since it basically is migrated from Sublime Text, which again was migrated from textMate

The "apm" command will do the trick i think – follow this discussion:

https://discuss.atom.io/t/convert-sublime-grammar-to-atom-grammar/14843

**Comment by NielsLiisberg** [comment]
Now - since the vsCode in the current version is moving away from the sublime/textMate language gramma, it will be more and more difficult, and i doubt I will support two code bases. So please stick to the vsCode, or give me some potent reasons to port it. Anyways - thank you for your interest, and give me a shout if you can't live without it.
